<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514184353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE page (id UUID NOT NULL, path TEXT NOT NULL, draft_content JSON DEFAULT NULL, live_content JSON DEFAULT NULL, title VARCHAR(255) NOT NULL, site_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_140AB620F6BD1646 ON page (site_id)');
        $this->addSql('CREATE TABLE site (id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_site (user_id UUID NOT NULL, site_id UUID NOT NULL, PRIMARY KEY (user_id, site_id))');
        $this->addSql('CREATE INDEX IDX_13C2452DA76ED395 ON user_site (user_id)');
        $this->addSql('CREATE INDEX IDX_13C2452DF6BD1646 ON user_site (site_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_site ADD CONSTRAINT FK_13C2452DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_site ADD CONSTRAINT FK_13C2452DF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB620F6BD1646');
        $this->addSql('ALTER TABLE user_site DROP CONSTRAINT FK_13C2452DA76ED395');
        $this->addSql('ALTER TABLE user_site DROP CONSTRAINT FK_13C2452DF6BD1646');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_site');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
